#!/bin/bash
./install &&
cp languages/brainfuck/node_types.csv node_types.csv &&
psql -q -X -f languages/brainfuck.sql &&
mv node_types.csv languages/brainfuck/node_types.csv &&
psql -X -c "\
SET search_path TO soft, public, pg_temp; \
SELECT COUNT(Run(Language, Program)) \
FROM View_Programs \
WHERE Language = 'brainfuck' AND Program LIKE '%$1%'\
" &&
while true ; do clear ; \
psql -c "SELECT Language, Phase, OK, COUNT(*) FROM View_Tests GROUP BY 1,2,3 ORDER BY 1,2,3;" ; \
psql -c "SELECT * FROM View_Tests WHERE NOT OK ORDER BY TestID;" ; \
psql -c "SELECT pid,application_name,wait_event_type,wait_event,state,query FROM pg_stat_activity ORDER BY pid;" ; \
sleep 5; done
