ROLLBACK;
\set AUTOCOMMIT ON

CREATE TYPE public.batchjobstate AS ENUM (
    'AGAIN',
    'DONE'
);

DROP SCHEMA soft CASCADE;
DROP SCHEMA "TOKENIZE" CASCADE;
DROP SCHEMA "DISCARD" CASCADE;
DROP SCHEMA "PARSE" CASCADE;
DROP SCHEMA "REDUCE" CASCADE;
DROP SCHEMA "MAP_VARIABLES" CASCADE;
DROP SCHEMA "EVAL" CASCADE;
DROP SCHEMA "BUILT_IN_FUNCTIONS" CASCADE;
\set AUTOCOMMIT OFF
BEGIN;
\ir soft.sql
COMMIT;
