ROLLBACK;
\set AUTOCOMMIT ON
DROP SCHEMA soft CASCADE;
DROP SCHEMA "TOKENIZE" CASCADE;
DROP SCHEMA "DISCARD" CASCADE;
DROP SCHEMA "PARSE" CASCADE;
DROP SCHEMA "REDUCE" CASCADE;
DROP SCHEMA "MAP_VARIABLES" CASCADE;
DROP SCHEMA "MAP_FUNCTIONS" CASCADE;
DROP SCHEMA "MAP_ALLOCA" CASCADE;
DROP SCHEMA "EVAL" CASCADE;
\set AUTOCOMMIT OFF
BEGIN;
\ir soft.sql
COMMIT;
