#!/bin/bash
# In another terminal, run:
# while true ; do PGUSER=pgcronjob PGDATABASE=$USER ./pgcronjob ; psql -X -f install.sql ; done
killall perl # to kill pgcronjob
sleep 1
./install &&
cp languages/lox/node_types.csv node_types.csv &&
psql -q -X -f languages/lox.sql &&
mv node_types.csv languages/lox/node_types.csv &&
while true ; do clear ; psql -c "SELECT * FROM View_Tests WHERE NOT OK;"; sleep 1; done
