#!/bin/bash
./install &&
cp languages/lox/node_types.csv node_types.csv &&
cp languages/lox/error_types.csv error_types.csv &&
psql -q -X -f languages/lox.sql &&
mv node_types.csv languages/lox/node_types.csv &&
mv error_types.csv languages/lox/error_types.csv &&
psql -X -c "\
SET search_path TO soft, public, pg_temp; \
SELECT COUNT(Run(Language, Program)) \
FROM View_Programs \
WHERE Language = 'lox' AND Program LIKE '%$1%'\
" &&
while true ; do clear ; psql -c "SELECT Language, Phase, OK, COUNT(*) FROM View_Tests GROUP BY 1,2,3 ORDER BY 1,2,3"; sleep 5; done
