#!/bin/bash
killall perl # to kill pgcronjob
sleep 1
./install
cp languages/lox/node_types.csv node_types.csv
psql -q -X -f languages/lox.sql
mv node_types.csv languages/lox/node_types.csv
while true ; do psql -c "SELECT OK, COUNT(*) FROM View_Tests GROUP BY OK;"; psql -c "SELECT * FROM View_Tests WHERE NOT OK;"; sleep 1; done
