CREATE OR REPLACE FUNCTION "DISCARD"."LEAVE_TEST_EXPECTED_STDOUT"(_NodeID integer)
RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
BEGIN
PERFORM Next_Node(_NodeID);
RETURN Discard_Node(_NodeID);
END;
$$;
