CREATE OR REPLACE FUNCTION "LLVM_IR"."ENTER_WRITE_STDOUT"(_NodeID integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
BEGIN
PERFORM LLVMIR(_NodeID, format($IR$
; >ENTER_WRITE_STDOUT %1$s
ret i32 %1$s
post_%1$s:
; <ENTER_WRITE_STDOUT %1$s
$IR$, _NodeID));
RETURN;
END;
$$;
