CREATE OR REPLACE FUNCTION "LLVM_IR"."ENTER_READ_STDIN"(_NodeID integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
BEGIN
PERFORM LLVMIR(_NodeID, format($IR$
; >ENTER_READ_STDIN %1$s
ret i32 %1$s
post_%1$s:
; <ENTER_READ_STDIN %1$s
$IR$, _NodeID));
RETURN;
END;
$$;
