CREATE OR REPLACE FUNCTION "LLVM_IR"."LEAVE_PROGRAM"(_NodeID integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
BEGIN
PERFORM LLVMIR(_NodeID, format($IR$
; >LEAVE_PROGRAM %1$s
ret i32 0
}
; <LEAVE_PROGRAM %1$s
$IR$, _NodeID));

RETURN;
END;
$$;
