CREATE OR REPLACE FUNCTION "MAP_FUNCTIONS"."ENTER_FUNCTION_DECLARATION"(_NodeID integer) RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
BEGIN
PERFORM Goto_Child(_NodeID);
PERFORM Set_Visited(_NodeID, NULL);
RETURN TRUE;
END;
$$;
