CREATE OR REPLACE FUNCTION Toggle_Visited(_NodeID integer)
RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
_OK boolean;
BEGIN
UPDATE Nodes
SET Visited = NOT Visited
WHERE NodeID = _NodeID
AND DeathPhaseID IS NULL
AND Visited IS NOT NULL
RETURNING TRUE INTO STRICT _OK;
RETURN TRUE;
END;
$$;
