CREATE TABLE Programs (
ProgramID       serial      NOT NULL,
LanguageID      integer     NOT NULL REFERENCES Languages(LanguageID),
Program         text        NOT NULL,
PhaseID         integer     NOT NULL REFERENCES Phases(PhaseID),
LogSeverity     severity    NOT NULL DEFAULT 'NOTICE',
Iterations      bigint      NOT NULL DEFAULT 0,
Started         boolean     NOT NULL DEFAULT FALSE,
BirthTime       timestamptz NOT NULL DEFAULT clock_timestamp(),
ProcessID       integer     REFERENCES cron.Processes(ProcessID),
DeathTime       timestamptz,
NodeID          integer,
Direction       direction   NOT NULL DEFAULT 'ENTER',
RunUntilPhaseID integer     REFERENCES Phases(PhaseID),
MaxIterations   bigint,
ResultType      regtype,
ResultValue     text,
ResultTypes     regtype[],
ResultValues    text[],
PRIMARY KEY (ProgramID),
UNIQUE (LanguageID, Program),
UNIQUE (ProcessID),
CHECK (PhaseID    <= RunUntilPhaseID),
CHECK (Iterations <= MaxIterations)
);
